### PR TITLE
Added bundle for production

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Zaary** [comment]
Production bundle already exists: [bundle.js](https://github.com/MooMooForge/MooMoo.js/blob/main/dist/bundle.js)

**Comment by NuroC** [comment]
lmao

**Comment by ghost** [comment]
Me when production bundle isn't minimified
Imagine using unminimified mangled jquery for production (???????)

**Comment by NuroC** [comment]
us jsdelivr

https://cdn.jsdelivr.net/gh/MooMooForge/MooMoo.js@main/dist/bundle.js
https://cdn.jsdelivr.net/gh/MooMooForge/MooMoo.js@main/dist/bundle.min.js

**Pull request closed without merging**
